### PR TITLE
CA-248467: message-cli tail --follow causes VM reboot too slow

### PR DESCRIPTION
**Pull request by DeliZhangX**
Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>

Hi Sir,
Please help to review this PR, you can get details about the issue from CA-248467 with my analysis.
The issue is little difficult to resolve thoroughly, while from my testing I prefer to this simple change, after all  message-cli is just a tool and it would not be used in general situation.
If you have any better idea please let me know.
Thanks,
Deli

### CODE REVIEW

**Comment by lindig** [comment]
Please add a meaningful commit message that explains why it is the right solution to change the timeout from 5 seconds to 0.5 seconds.

**Comment by DeliZhangX** [comment]
"message-cli tail --follow" sends a Trace request to message-switch, which handle process is 
below Cohttp_lwt_unix.Server callback function:
`callback in switch_main.ml
    ...
    Lwt_mutex.with_lock m

    process_request conn_id_s !queues session request
        | In.Trace(from, timeout) -> 
            Trace.get from timeout;
            ...
            Lwt.pick [ sleep; wait_for_data () ]
            ...
        | Some session, In.Ack (name, id) -> Trace.add
        | Some session, In.Transfer -> Trace.add
        | Some session, In.Send (name, data) -> Trace.add
`
The problem is that 
when process In.Trace message, the thread will be blocked by sleep or wait_for_data.
1. wait_for_data will return only if Trace.add is called which means new message of In.Ack， Transfer or Send received,
    but the fact is the callback thread has been blocked, no thread handle other coming messages.
    I am not sure while it's very possible the Cohttp_lwt_unix.Server is just single thread server,
    even if it's multi-thread server then the lock 'Lwt_mutex.with_lock m' will cause all other callback threads blocked here.
2. callback could work again once sleep timeout-ed, and the timeout value, default 5 seconds, is specified in "message-cli" of main.ml
`let tail common_opts follow =
    let timeout = 5. in`
 that's also why it improve the situation if modify timeout to 1 second.

**Comment by lindig** [comment]
The analysis on the ticket is convincing. Maybe add something simple: 

```
The timeout in message switch delays reboots - see CA-248467 for details. This commit
reduces the timeout from 5 seconds to 0.5 seconds to mitigate the problem.
```

**Comment by DeliZhangX** [comment]
Thank Lindig. As 'message-cli tail --follow' is just used for debugging, so I think mitigating the problem is effective and acceptable. Sure if it needs absolute solution then I am willing to spend more time to change code (will make it more complex) and test, while the only concern is whether it's worth :)

**Comment by lindig** [comment]
I'm fine with the solution. I'd just like to see the commit message updated as suggested with something that provided the context of this change:

```
The timeout in message-switch delays reboots - see CA-248467 for details. This commit
reduces the timeout from 5 seconds to 0.5 seconds to mitigate the problem. This is most 
relevant in the context of debugging where message-cli tail --follow is being used.
```

**Comment by jonludlam** [comment]
Hold on a tick. I'm very unconvinced by this. There's already a pre-existing blocking connection that doesn't cause other callers to queue - Transfer. This is dealt with outside of the mutex-protected code here:

https://github.com/xapi-project/message-switch/blob/master/switch/switch_main.ml#L237-L255

Why can't we follow a similar pattern for Trace?

**Comment by DeliZhangX** [comment]
Hi jonludlam, 
https://github.com/xapi-project/message-switch/blob/master/switch/switch_main.ml#L237-L255 is just a part of Transfer handling, which does not call Trace.add() where the Lwt_condition c of Trace module would broadcast, that indicates wait_for_data () will still block on Lwt_condition.wait c.
If move Trace handling to out of Lwt_mutex.with_lock m, then some data struct will be not threadsafe. e.g. the Trace.buffer, one callback thread maybe reading it meanwhile another callback thread calls Trace.add() to write it.

**Comment by jonludlam** [comment]
Indeed, so you may need to use a different mutex or perhaps rearrange the code a little more. However, the point still stands that it's entirely possible to fix the issue properly without resorting to effectively a polling API.

**Comment by DeliZhangX** [comment]
Hi jonludlam,
As talked before, unlock that mutex m before Lwt_condition.wait c resolved the problem indeed.
I looked up Lwt document, Lwt_condition supports the case properly, so the solution should be most concise.
Please help to review again.
Thanks

**Comment by mseri** [comment]
That's much nicer and concise!

**Comment by jonludlam** [comment]
Much nicer! Thanks for putting in the additional effort, I think this is a far better solution.

**Pull request merged**
