### PR TITLE
message-switch-core.opam: we use rpclib not the old rpc

### PR DESCRIPTION
**Pull request by edwintorok**
rpc depends on both async and lwt, rpclib allows us to bring in just the one we need

### CODE REVIEW

**Comment by edwintorok** [comment]
Looks like ppx_deriving_rpc was missing (previously this came in  transitively  through `rpc`).

**Comment by edwintorok** [comment]
Looks like we also have to specify the DISTRO, otherwise it picks a default that doesn't have 4.06 in it and tries to build 4.06 as part of the travis build of the PR

**Comment by lindig** [comment]
This works: 
```
language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE=message-switch
    - PINS="message-switch-async:. message-switch-cli:. message-switch-core:.  message-switch:.  message-switch-lwt:.  message-switch-unix:."
    - BASE_REMOTE="https://github.com/xapi-project/xs-opam.git"
  matrix:
    - DISTRO="debian-9-ocaml-4.06"
      # - DISTRO="debian-8-ocaml-4.07" BASE_REMOTE_BRANCH="407"
```

**Comment by edwintorok** [comment]
Thanks, I think I overlooked that the old .travis.yml was using .travis-opam.sh instead of .travis-docker.sh

**Pull request merged**
